version: '3.8'

services:
  asset-transfer-service:
    image: asset-transfer-basic
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7051:7051"
    environment:
      - CC_SERVER_PORT=7051
    restart: unless-stopped
    user: "node"
    entrypoint: ["/tini", "--", "/usr/src/app/docker-entrypoint.sh"]
