import Header from "@/components/header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SidebarContextWrapper } from "@/context/sidebar";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { AuthenticatedContextWrapper } from "@/context/authentication";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Organization service",
  description: "REC project. Generated by Cryptic Consultancy Limited",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SidebarContextWrapper>
          <AuthenticatedContextWrapper>
          <ToastContainer />
          <Header />
          {children}
          </AuthenticatedContextWrapper>
        </SidebarContextWrapper>
      </body>
    </html>
  );
}
